### ISSUE TITLE
Are a Date Field and a Currency Field planned to be implemented?

### ISSUE THREAD

**Issue by RobertoMalatesta** [john-doherty/pure-form#21]
Hi John,

again :P, this time for a question:

Are a Date Field and a Currency Field planned to be implemented?

Thanks for your time,

-- Rob

**Comment by john-doherty** [comment]
Hi @RobertoMalatesta 'pure-form' already supports `"format": "date"` but currency needs adding. 

As a workaround, you can use a custom URN as the value of `format` to create any tag you like, for example the JSON Schema entry:

```json
"unlockPin": {
    "title": "Enter PIN to unlock",
    "type": "string",
    "pattern": "[0-9]*",
    "format": "custom:input;type=text,data-action=confirmpin,data-trigger=keyup"
}
```

Creates:

```
<input name="unlockPin" type="text" data-action="confirmpin" 
    data-trigger="keyup" pattern="[0-9]*" />
```

To break the URN apart:

 * **custom:** 
 Tells pure-form to create a custom HTML element

 * **input**
 The second param is the HTML tagName to create

 * **type=text,data-action=confirmpin,data-trigger=keyup**
 Followed by the HTML attributes and values
