### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by brrd** [john-doherty/pure-form#23]
First of all, thank you for this great and useful library!

Obviously pure-form is not published yet on npm: https://www.npmjs.com/package/pure-form

@john-doherty could you publish this package on npm in order to make it easier to manage as a dependency? I believe it is better if the actual developer is also the maintainer of the npm package. Most npm packages are not up-to-date when this is not the case.

**Comment by john-doherty** [comment]
Thanks @brrd, it's now on npm :)
